#!/usr/bin/env python3
"""Regenerate acid/manifest.txt from the vendored GBEmulatorShootout suite
definitions in acid/defs/.

The defs are verbatim copies of testroms/*.py from
https://github.com/trekawek/GBEmulatorShootout — to sync with upstream, copy
the new testroms payload over acid/ and the new testroms/*.py over acid/defs/,
then rerun this script.

Each def file does `from test import *` and builds `all = [Test(...), ...]`.
We satisfy that import with a stub `test` module whose Test class only records
arguments and resolves image paths (upstream's opens them with PIL).

Manifest line format (paths relative to acid/):
    name|model|runtime_seconds|rom|pass_png[;pass_png...]|fail_png[;...]
A test with no pass images is informational (never fails).
"""

import os
import sys
import types

ACID_ROOT = os.path.dirname(os.path.abspath(__file__))

# Suite concatenation order copied from upstream main.py.
SUITE_ORDER = ["acid", "blargg", "daid", "ax6", "mooneye",
               "samesuite", "ashiepaws", "cpp", "mealybug"]


def make_stub_test_module():
    mod = types.ModuleType("test")
    mod.PASS = "PASS"
    mod.FAIL = "FAIL"
    mod.INFO = "INFO"
    mod.DMG = "DMG"
    mod.CGB = "CGB"
    mod.SGB = "SGB"
    mod.PCM = "PCM"

    class Test:
        def __init__(self, name, *, runtime, rom=None, result=None, model="DMG",
                     required_features=None, description=None, url=None, tags=None):
            rom = rom or name
            self.name = name
            self.rom = rom
            self.model = model
            self.runtime = runtime
            self.required_features = set(required_features or ())

            rom_abs = os.path.join(ACID_ROOT, rom)
            if not os.path.exists(rom_abs):
                raise FileNotFoundError(rom_abs)

            if result is None:
                result = os.path.splitext(rom)[0] + ".png"
            if not isinstance(result, list):
                result = [result]
            self.pass_images = [r for r in result
                                if os.path.exists(os.path.join(ACID_ROOT, r))]
            self.fail_images = []
            for r in result:
                f = os.path.splitext(r)[0] + ".fail.png"
                if os.path.exists(os.path.join(ACID_ROOT, f)):
                    self.fail_images.append(f)

        def __repr__(self):
            return self.name

    mod.Test = Test
    return mod


def main():
    sys.modules["test"] = make_stub_test_module()

    tests = []
    for suite in SUITE_ORDER:
        path = os.path.join(ACID_ROOT, "defs", suite + ".py")
        ns = {"__file__": path, "__name__": "defs." + suite}
        with open(path, "r", encoding="utf-8") as f:
            code = f.read()
        exec(compile(code, path, "exec"), ns)
        tests.extend(ns["all"])

    out_path = os.path.join(ACID_ROOT, "manifest.txt")
    with open(out_path, "w", newline="\n", encoding="utf-8") as f:
        f.write("# Generated by make_manifest.py from acid/defs/ - do not hand-edit.\n")
        f.write("# name|model|runtime_seconds|rom|pass_images|fail_images\n")
        for t in tests:
            f.write("%s|%s|%g|%s|%s|%s\n" % (
                t.name, t.model, t.runtime, t.rom.replace("\\", "/"),
                ";".join(t.pass_images), ";".join(t.fail_images)))

    n_info = sum(1 for t in tests if not t.pass_images)
    print("wrote %s: %d tests (%d with pass images, %d info-only)"
          % (out_path, len(tests), len(tests) - n_info, n_info))
    by_model = {}
    for t in tests:
        by_model[t.model] = by_model.get(t.model, 0) + 1
    print("models:", by_model)


if __name__ == "__main__":
    main()
